application/urls.py
from django.urls import path
from . import views

app_name = 'application'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
]

pjt1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('application.urls'))
]

application/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

application/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('article',)

application/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('application:index')
    else:
        form=ArticleForm()

    context={
        'form': form,
    }
    return render(request, 'form.html', context)
        
        
def detail(request,id):
    article = Article.objects.get(id=id)

    comment_form = CommentForm()

    context = {
        'article': article,
        'comment_form': comment_form
    }

    return render(request, 'detail.html', context)

def comment_create(request, article_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        comment.article_id = article_id

        comment.save()

        return redirect('application:detail', id=article_id)
    
def comment_delete(request, article_id,id):
    comment = Comment.objects.get(id=id)

    comment.delete()

    return redirect('application:detail', id=article_id)

application/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>{{article.title}}</h1>
<p>{{article.content}}</p>

<hr>

    <form action="{% url 'application:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit">

    </form>

    {% if not article.comment_set.all|length %}
        <p>댓글이 없습니다.</p>
    {% endif %}

    {% for comment in article.comment_set.all %}
        <p>{{comment.content}}
        <a href="{% url 'application:comment_delete' article_id=article.id id=comment.id %}">X</a>
        </p>
    {% endfor %}

{% endblock %}

application/templates/form.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">

</form>

{% endblock %}

application/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'application:detail' id=article.id %}">detail</a>
        <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'application:index' %}">Home</a>
    <a href="{% url 'application:create' %}">Create</a>
    {% block body %}
    {% endblock %}
</body>
</html>